DROP TABLE IF EXISTS commodities.webuycars;
CREATE TABLE commodities.webuycars (
  category VARCHAR,
  subcategory VARCHAR,
  filter_category VARCHAR,
  colour VARCHAR,
  condition VARCHAR,
  dealer_key VARCHAR,
  branch_code VARCHAR,
  province VARCHAR,
  description VARCHAR,
  make VARCHAR,
  model VARCHAR,
  mileage INTEGER,
  online_description VARCHAR,
  variant VARCHAR,
  price INTEGER,
  stock_number VARCHAR,
  internal_stock_number VARCHAR,
  buy_lead_code VARCHAR,
  year INTEGER,
  vehicle_barcode VARCHAR,
  axle_configuration VARCHAR,
  body_type VARCHAR,
  no_of_doors VARCHAR,
  drive VARCHAR,
  seats VARCHAR,
  use VARCHAR,
  gearbox VARCHAR,
  no_gears VARCHAR,
  cooling VARCHAR,
  cubic_capacity VARCHAR,
  cyl_configuration VARCHAR,
  engine_cycle VARCHAR,
  fuel_tank_size VARCHAR,
  fuel_type VARCHAR,
  fuel_consumption FLOAT,
  fuel_highway INTEGER,
  fuel_urban INTEGER,
  boot_capacity INTEGER,
  towing_capacity INTEGER,
  acceleration FLOAT,
  disk_drive_unique_reference VARCHAR,
  kilowatts VARCHAR,
  no_cylinders VARCHAR,
  gcm VARCHAR,
  gvm VARCHAR,
  tare VARCHAR,
  front_no_tyres VARCHAR,
  front_tyre_size VARCHAR,
  rear_no_tyres VARCHAR,
  rear_tyre_size VARCHAR,
  co2 VARCHAR,
  length VARCHAR,
  height VARCHAR,
  width VARCHAR,
  active_warranty BOOLEAN,
  active_maintenance BOOLEAN,
  mm_code_frequency VARCHAR,
  mm_code_frequency_weight INTEGER,
  opening_bid INTEGER,
  buy_now_price INTEGER,
  service_history VARCHAR,
  license_disk VARCHAR,
  has_spare_key BOOLEAN,
  stock_status VARCHAR,
  status VARCHAR,
  finance_grade VARCHAR,
  pricing_grade VARCHAR,
  last_price_update_date VARCHAR,
  vin VARCHAR,
  vehicle_status VARCHAR,
  assigned_parking_bay VARCHAR,
  monthly_instalment INTEGER,
  vehicle_type VARCHAR,
  previous_price INTEGER,
  has_any_roadworthy_relevant_issues BOOLEAN,
  roadworthy_relevant_issues INTEGER,
  has_dekra_voucher BOOLEAN,
  has_roadworthy_completed BOOLEAN,
  video_review_url VARCHAR,
  eval_service_history VARCHAR,
  eval_maintenance_active BOOLEAN,
  eval_warranty_active BOOLEAN,
  eval_has_car_play_android_auto BOOLEAN,
  eval_has_reverse_camera BOOLEAN,
  eval_has_auto_stop_start BOOLEAN,
  default_sort_order INTEGER,
  stock_tag VARCHAR,
  stock_flag VARCHAR,
  has_dekra_green BOOLEAN,
  has_dekra_gold BOOLEAN,
  has_dekra_platinum BOOLEAN,
  dekra_type VARCHAR,
  sync_hash VARCHAR,
  turbo_or_super_charged VARCHAR,
  last_service_date VARCHAR,
  last_service_km FLOAT,
  search_tag VARCHAR,
  warranty_expiry_date VARCHAR,
  service_plan_expiry_date VARCHAR,
  eval_warranty_expiry VARCHAR,
  wheelbase VARCHAR,
  maintenance_plan_expiry_date VARCHAR,
  eval_maintenance_expiry VARCHAR,
  lot_category VARCHAR,
  reserve_price INTEGER,
  reserve_price_met BOOLEAN
)
WITH (
  appendonly = true,
  compresstype = zlib,
  compresslevel = 5,
    orientation = column
)
DISTRIBUTED RANDOMLY;

CREATE TABLE commodities.webuycars_dates (
    scrape_date DATE, 
    stock_number VARCHAR
)
WITH (
  appendonly = true,
  compresstype = zlib,
  compresslevel = 5,
    orientation = column
)
DISTRIBUTED RANDOMLY;